export const ACTIVE_FILTERS_UPDATE = 'ACTIVE_FILTERS_UPDATE';

export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';

export const TICKETS_FETCH_REQUEST = 'TICKETS_FETCH_REQUEST';
export const TICKETS_FETCH_SUCCESS = 'TICKETS_FETCH_SUCCESS';
export const TICKETS_FETCH_FAILURE = 'TICKETS_FETCH_FAILURE';
